language: php

php:
  - 5.3
  - 5.4

before_script:
  # export virtual display
  - export DISPLAY=:99

  # change application working folders for write access
  - chmod -R 0777 ./tmp
  - chmod -R 0777 ./uploads
  - chmod -R 0777 ./templates/cache/
  - chmod -R 0777 ./templates/compiled/
  - mv ./install ./install.dist
  - cp install.dist/*.sql tests/fixtures/sql/

  # install required PHP stuff
  - sudo apt-get update
  - sudo apt-get install php5 php5-cli php5-mysql php5-mcrypt php5-xsl php5-xdebug php-apc php5-gd php5-curl php5-intl mysql-server mysql-client

  # launch apache, MySQL and PHPUnit Selenium installers
  - ./tests/travis/apache_setup.sh
  - cp ./config/config.test.php.dist config/config.test.php
  - cp ./config/config.test.php.dist config/config.local.php
  - sudo sed -i s/sql-mode/#sql-mode/ /etc/mysql/my.cnf
  - sudo /etc/init.d/mysql restart
  - sleep 5

  # get HTML of main page (for debug)
  
  - ls -la ./install.dist/
  - ls -la ./tests/fixtures/sql/

  - firefox --version
  - wget -S http://livestreet.test -O /dev/null

  # start virtual display
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # download and launch Selenium
  - wget -O /tmp/selenium-server-standalone.jar http://selenium.dev.stfalcon.com/selenium-server-standalone-latest.jar
  - java -jar /tmp/selenium-server-standalone.jar > /dev/null &
  - sleep 5


script: HTTP_APP_ENV=test php tests/behat/behat.phar -c tests/behat/behat.yml
